# WEB PROPERTIES
server:
  port: 8080
  context-path: '/'

# SPRING
spring:
  # DATASOURCE
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: 'jdbc:mysql://localhost:3306/admin3?useUnicode=true&characterEncoding=UTF-8'
    username: root
    password: 123456

  jpa:
    show-sql: false

# LOGGING
logging:
  level:
        org.springframework.jdbc: info

buoy:
  server-path: http://192.168.1.51:9010/buoy

pet:
  server-path: https://diyiliu.cc:880